SENSORS_DICT = {
    'air_temp': {
        'key': 'air_temp',
        'fields': {'air_temp': 'Lufttemperatur',},
        'label': 'Lufttemperatur [°C]',
        'station_db_table': "T_100009_station",
        'db_table': "T_100009_temperature",
        'map_config': {
            'station_agg_function': 'avg',
            'lat': 'lat',
            'long': 'long',
            'station_col': 'station_id',
            'value_col': 'value',
            'width': 600,
            'height': 600,
            'fig_text': {'avg': 'Mittlere {} Lufttemperatur [°C] pro Station',
                            'min': 'Minimale {} Lufttemperatur [°C] pro Station',
                            'max': 'Maximale {} Lufttemperatur [°C] pro Station',
                            'std': 'Standardabweichung {} Lufttemperatur [°C] pro Station',
                        },
        },
        'histogram_config': {
            'x': 'value',
            'x_title': '',
            'y_title': 'Anzahl',
            'bins': 20,
            'x_domain': [0.100],
            'width': 600,
            'height': 400,
            'fig_text': {'avg': 'Histogramm der Durchschnitts-Lufttemperatur [°C] für {} Stationen.',
                            'min': 'Histogramm der minimalen Lufttemperatur [°C] für {} Stationen.',
                            'max': 'Histogramm der maximalen Lufttemperatur [°C] für {} Stationen.',
                            'std': 'Histogramm der Standardaweichung der Lufttemperatur [°C] pro Station'
                        }
        },
        'timeseries_config': {
            'y': 'value',
            'title': '',
            'width': 1000,
            'height': 300,
            'x_title': '',
            'y_digits': 1,
            'color': 'station',
            'marker_size': 30,
            'ts_time_field': {'date': 'hour_date', 'week_date': 'hour_date', 'month_date': 'hour_date', 'year_date': 'date'},
            'ts_time_format': {'date': '%H:%M', 'week_date': '%d.%m.%Y', 'month_date': '%d.%m.%y', 'year_date': '%d.%m.%y'}
            
        },
        'intro': """**Lufttemperatur [°C]**<br>Die Lufttemperatur wird an {} Stellen gemessen.<br>Quelle: [opendata.bs](https://data.bs.ch/explore/dataset/100009/information/)"""
    },
    'precipitation': {
        'key': 'precipitation',
        'fields': {'precipitation': 'Niederschlag',},
        'label': 'Niederschlag [mm]',
        'station_db_table': "T_100009_station",
        'db_table': "T_100009_prec",
        'map_config': {
            'station_agg_function': 'avg',
            'lat': 'lat',
            'long': 'long',
            'station_col': 'station_id',
            'value_col': 'value',
            'station_id': 'station_id',
            'size': 50,
            'width': 600,
            'height': 600,
            'fig_text': {'avg': 'Mittlerer {} Niederschlag [°C] pro Station',
                            'min': 'Minimaler {} Niederschlag [°C] pro Station',
                            'max': 'Maximaler {} Niederschlag [°C] pro Station',
                            'sum': 'Summe {} Niederschlag [°C] pro Station'
                        }
        },
        'histogram_config': {
            'x': 'value',
            'x_title': '',
            'y_title': 'Anzahl',
            'bins': 20,
            'x_domain': [0.100],
            'width': 600,
            'height': 400,
            'fig_text': {'avg': 'Histogramm der Durchschnitts-Niederschlags [°C] für {} Stationen.',
                            'min': 'Histogramm des minimalen Niederschlags [°C] für {} Stationen.',
                            'max': 'Histogramm des maximalen Niederschlags [°C] für {} Stationen.',
                            'sum': 'Histogramm des Niederschlags [°C] pro Station, {} Stationen'
                        }
        },
        'timeseries_config': {
            'y': 'value',
            'title': '',
            'width': 1000,
            'height': 300,
            'x_title': '',
            'y_digits': 1,
            'color': 'station',
            'marker_size': 30,
            'ts_time_field': {'date': 'date', 'week_date': 'date', 'month_date': 'date', 'year_date': 'date'},
            'ts_time_format': {'date': '%H:%M', 'week_date': '%d.%m.%Y', 'month_date': '%d.%m.%y', 'year_date': '%d.%m.%y'}
        },
        'intro': """**Niederschlag [mm]**<br>Der Niederschlag wird an {} Stellen gemessen. Die Messung erfolgt in der Regel stündlich, kann aber auch unregelmässig erfolgen und es wird jeweils die Differenz zur letzten Messung in mm rapportiert. Um eine sinnvolle grafisch und numerische Aufbereitung er ermöglichen wurden die Differenzen der Werte pro Tag summiert, sodass Vergleiche pro Tag möglich sind, nicht aber für Stundenwerte.<br>Quelle: [opendata.bs](https://data.bs.ch/explore/dataset/100009/information/)"""
    },

     'noise': {
        'key': 'noise',
        'fields': {'min_noise': 'Lärm_min', 'max_noise': 'Lärm_max', 'mean_noise': 'Lärm_durchschn'},
        'label': 'Lärm [dB]',
        'station_db_table': "T_100087_station",
        'db_table': "T_100087",
        'map_config': {
            'station_agg_function': 'avg',
            'lat': 'lat',
            'long': 'long',
            'station_col': 'station_id',
            'value_col': 'value',
            'min_val': 0,
            'max_val': 10,
            'station_id': 'station_id',
            'size': 50,
            'width': 600,
            'height': 600,
            'map_time_field': 'date',
            'fig_text': {'avg': 'Mittlere {} Lärmpegerl [°C] pro Station',
                            'min': 'Minimaler {} Lärmpegel [°C] pro Station',
                            'max': 'Maximaler {} Lärmpegel [°C] pro Station',
                            'std': 'Standardabweichung des {} Lärmpegels [°C] pro Station',
                            'sum': 'Summe {} Lärmpegel [°C] pro Station'}
        },
        'histogram_config': {
            'x': 'value',
            'x_title': '',
            'y_title': 'Anzahl',
            'bins': 20,
            'x_domain': [0.100],
            'width': 600,
            'height': 400,
            'fig_text': {'avg': 'Histogramm der Durchschnitts-Lärmpegels [°C] für {} Stationen.',
                            'min': 'Histogramm des minimalen Lärmpegels [°C] für {} Stationen.',
                            'max': 'Histogramm des maximalen Lärmpegels [°C] für {} Stationen.'}
        },
        'timeseries_config': {
            'y': 'value',
            'title': '',
            'width': 1000,
            'height': 300,
            'x_title': '',
            'y_digits': 1,
            'color': 'station',
            'marker_size': 30,
            'ts_time_field': {'date': 'hour_date', 'week_date': 'hour_date', 'month_date': 'hour_date', 'year_date': 'date'},
            'ts_time_format': {'date': '%H:%M', 'week_date': '%d.%m.%Y', 'month_date': '%d.%m.%y', 'year_date': '%d.%m.%y'}
        },
        'intro': """**Lärm [dB]**</br>Der Verkehrslärm wird an {} Stellen gemessen.<br>Quelle: [opendata.bs](https://data.bs.ch/explore/dataset/100087/information/)"""
    },

    'particles_pm25': {
        'key': 'pm 2.5',
        'fields': {'pm25': 'PM 2.5'},
        'label': 'Feinstab PM2.5 [ug/m3]',
        'station_db_table': "T_100081_station",
        'db_table': "T_100081",
        'map_config': {
            'station_agg_function': 'avg',
            'lat': 'lat',
            'long': 'long',
            'station_col': 'station_id',
            'value_col': 'value',
            'min_val': 0,
            'max_val': 10,
            'station_id': 'station_id',
            'size': 50,
            'width': 600,
            'height': 600,
            'fig_text': {'avg': 'Mittlere {} Partikelkonzentration [°C] pro Station',
                            'min': 'Minimaler {} Partikelkonzentration [°C] pro Station',
                            'max': 'Maximaler {} Partikelkonzentration [°C] pro Station',
                            'std': 'Standardabweichung der {} Partikelkonzentration [°C] pro Station',
                            'sum': 'Summe {} Partikelkonzentration [°C] pro Station'}
        },
        'histogram_config': {
            'x': 'value',
            'x_title': '',
            'y_title': 'Anzahl',
            'bins': 20,
            'x_domain': [0.100],
            'width': 600,
            'height': 400,
            'fig_text': {'avg': 'Histogramm der Durchschnitts-Lärmpegels [°C] für {} Stationen.',
                            'min': 'Histogramm des minimalen Lärmpegels [°C] für {} Stationen.',
                            'max': 'Histogramm des maximalen Lärmpegels [°C] für {} Stationen.'}
        },
        'timeseries_config': {
            'y': 'value',
            'title': '',
            'width': 1000,
            'height': 300,
            'x_title': '',
            'y_digits': 1,
            'color': 'station',
            'marker_size': 30,
            'ts_time_field': {'date': 'hour_date', 'week_date': 'hour_date', 'month_date': 'hour_date', 'year_date': 'date'},
            'ts_time_format': {'date': '%H:%M', 'week_date': '%d.%m.%Y', 'month_date': '%d.%m.%y', 'year_date': '%d.%m.%y'}
        },
        'intro': """**Feinstab PM 2.5 [ug/m3]**</br>Feinstab der Partikelgrösse bis 2.5 μm wird an {} Stellen gemessen.<br>Quelle: [opendata.bs](https://data.bs.ch/explore/dataset/100081/information/)"""
    },
}